[package]
name = "synacor-challenge"
version = "0.1.0"
authors = ["qiaob"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
byteorder = "1"
